### PR TITLE
Improve test_name fixture by only removing the 'firmware' parameter

### PR DESCRIPTION
**Pull request by fbeutin-ledger**

### CODE REVIEW

**Review by xchapron-ledger — COMMENTED** [review]
Looks interesting but this will break some snapshot location on some app :/
Might still be worth it.

**Comment by fbeutin-ledger** [comment]
> Looks interesting but this will break some snapshot location on some app :/ Might still be worth it.
I know, but it's needed for this:
https://github.com/LedgerHQ/app-exchange/blob/fbe/exchange_test_runner/test/python/test_stellar.py

Currently our tests using parametrization cannot use the navigation which is unfortunate
OR they can modify the `test_name` locally 🤔

**Comment by xchapron-ledger** [comment]
> > Looks interesting but this will break some snapshot location on some app :/ Might still be worth it.
> > I know, but it's needed for this:
> > https://github.com/LedgerHQ/app-exchange/blob/fbe/exchange_test_runner/test/python/test_stellar.py
> 
> Currently our tests using parametrization cannot use the navigation which is unfortunate OR they can modify the `test_name` locally thinking

Yep, that's what I'm using here: https://github.com/LedgerHQ/app-eos/blob/ea123cd6d9ac7ec8f24ba0a34e3073badaf735e5/tests/functional/test_sign_cmd.py#L50-L53
But I can change it obviously.

**Comment by fbeutin-ledger** [comment]
Dropped, to handle in tests

**Pull request closed without merging**
